### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/bc_election_turnout#34]
Great proposal, I think the question is well defined and the analysis plan is laid out clearly. The EDA correlation figure did make it long though, so I don't think you needed to include that.

**Comment by rtaph** [comment]
Thanks @abaghela ! @ChadNeald, @yuanxiongbear, and @Kamal12073, what do you say if we prune down the README to include only the scatterplot (remove the tables, violin, and correlation matrix)?

**Comment by kmoravej** [comment]
Thanks @abaghela for the feedback. I believe we do not need to have a detailed readme since we have to prepare a report  Milestone II. We can make the current Readme shorter and more concise and then use the report to explain our problem and our analysis in more details. What do you think? @rtaph @yuanxiongbear @ChadNeald?

**Comment by yuanxiongbear** [comment]
Yea it sounds good to me. Based on milstone 2 we need to modify README.md anyway. We can make it shorter and includes some analysis in the script 5?

**Comment by rtaph** [comment]
Closed via #41.
