### ISSUE TITLE
Add a teamwork contract

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/bc_election_turnout#4]

**Comment by ChadNeald** [comment]
Reviewer: Kamal

**Comment by yuanxiongbear** [comment]
Hello,

Raf suggested me to create contract file using UBC onedrive. But I encountered an issue. I didn't register the @student.ubc.ca email because I have an alumina email. When I activated it last night it says expects 48h to be able to log into UBC onedrive using the new @student.ubc.ca email address. And I tried this morning still cant log into UBC onedrive. 

So can I use a md file for our contract? What do you think?

**Comment by rtaph** [comment]
@yuanxiongbear, let's pick something that is easy while also not putting sensitive information out publicly. I suggest either scrubbing the team contract for personally identifying information and posting it in this repo publicly, or put the `.md` as a gist on UBC's GHE, so that anyone on that account can follow the link to that file.

**Comment by yuanxiongbear** [comment]
Got it Raf, I will remove all the personal informations.
